warehouse_settings = {
    "Bodega Bucaramanga": {
        "fixed_cost": 0.6,
        "time_cost": 0.001,
        "distance_cost": 0,
        "stop_cost": 0.05,
        "excess_cost": 0.1,
        "penalty_cost": 0.1,
        "maximum_excess": 0.1,
        "maximum_penalties": 0,
        "release_weight": 0.2,
        'warehouse_return': False
    },
    "Bodega Medellin": {
        "fixed_cost": 0.6,
        "time_cost": 0.001,
        "distance_cost": 0,
        "stop_cost": 0.05,
        "excess_cost": 0.1,
        "penalty_cost": 0.1,
        "maximum_excess": 0.1,
        "maximum_penalties": 0,
        "release_weight": 0.2,
        'warehouse_return': False
    },
    "bodega Fontibon": {
        "fixed_cost": 0.6,
        "time_cost": 0.001,
        "distance_cost": 0,
        "stop_cost": 0.05,
        "excess_cost": 0.1,
        "penalty_cost": 0.1,
        "maximum_excess": 0.1,
        "maximum_penalties": 0,
        "release_weight": 0.2,
        'warehouse_return': False
    },
    "Bodega Fontibon": {
        "fixed_cost": 0.6,
        "time_cost":  0.001,
        "distance_cost": 0,
        "penalty_cost": 0.1,
        "excess_cost": 0.1,
        "stop_cost": 0.05,
        "maximum_penalties": 0,
        "maximum_excess": 0.1,
        "release_weight": 0.2,
        'warehouse_return': False
    },
    "Bodega Barranquilla": {
        "fixed_cost": 0.6,
        "time_cost":  0.001,
        "distance_cost": 0,
        "penalty_cost": 0.1,
        "excess_cost": 0.1,
        "stop_cost": 0.05,
        "maximum_penalties": 0,
        "maximum_excess": 0.1,
        "release_weight": 0.2,
        'warehouse_return': False
    },
    "Bodega Cali": {
        "fixed_cost": 0.6,
        "time_cost": 0.001,
        "distance_cost": 0,
        "stop_cost": 0.05,
        "excess_cost": 0.1,
        "penalty_cost": 0.1,
        "maximum_excess": 0.1,
        "maximum_penalties": 0,
        "release_weight": 0.2,
        'warehouse_return': False
    },
    "Quito": {
        "fixed_cost": 0.6,
        "time_cost": 0.001,
        "distance_cost": 0,
        "stop_cost": 0.05,
        "excess_cost": 0.1,
        "penalty_cost": 0.1,
        "maximum_excess": 0.1,
        "maximum_penalties": 0,
        "release_weight": 0.2,
        'warehouse_return': False
    },
    "Guayaquil": {
        "fixed_cost": 0.6,
        "time_cost": 0.001,
        "distance_cost": 0,
        "stop_cost": 0.05,
        "excess_cost": 0.1,
        "penalty_cost": 0.1,
        "maximum_excess": 0.1,
        "maximum_penalties": 0,
        "release_weight": 0.2,
        'warehouse_return': False
    },
    "Guadalajara - México": {
        "fixed_cost": 0.6,
        "time_cost": 0.001,
        "distance_cost": 0,
        "stop_cost": 0.05,
        "excess_cost": 0.1,
        "penalty_cost": 0.1,
        "maximum_excess": 0.1,
        "maximum_penalties": 0,
        "release_weight": 0.2,
        'warehouse_return': False
    },
    "Tlalnepantla": {
        "fixed_cost": 0.6,
        "time_cost":  0.001,
        "distance_cost": 0,
        "penalty_cost": 0.1,
        "excess_cost": 0.1,
        "stop_cost": 0.05,
        "maximum_penalties": 0,
        "maximum_excess": 0.1,
        "release_weight": 0.2,
        'warehouse_return': False
    },
    "Sao Pablo": {
        "fixed_cost": 1,
        "time_cost": 0.001,
        "distance_cost": 0,
        "stop_cost": 0.05,
        "excess_cost": 0.1,
        "penalty_cost": 0.1,
        "maximum_excess": 0.1,
        "maximum_penalties": 0,
        "release_weight": 0.2,
        'warehouse_return': False
    },
    "Instance": {
        "fixed_cost": 0,
        "time_cost": 1,
        "distance_cost": 0,
        "stop_cost": 0,
        "excess_cost": 0,
        "penalty_cost": 0,
        "maximum_excess": 0,
        "maximum_penalties": 0,
        "release_weight": 0,
        'warehouse_return': True
    }
}